-- MySQL Script generated by MySQL Workbench
-- Mon Mar 14 13:56:29 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ftk09_carrosserie_proissy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ftk09_carrosserie_proissy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ftk09_carrosserie_proissy` DEFAULT CHARACTER SET utf8 ;
USE `ftk09_carrosserie_proissy` ;

-- -----------------------------------------------------
-- Table `ftk09_carrosserie_proissy`.`ftk09_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ftk09_carrosserie_proissy`.`ftk09_admin` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(250) NOT NULL,
  `mail` VARCHAR(250) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `ftk09_carrosserie_proissy`.`ftk09_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ftk09_carrosserie_proissy`.`ftk09_image` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `description` TEXT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `ftk09_carrosserie_proissy`.`ftk09_messagerie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ftk09_carrosserie_proissy`.`ftk09_messagerie` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sender` VARCHAR(255) NOT NULL,
  `messages` TEXT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `ftk09_carrosserie_proissy`.`ftk09_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ftk09_carrosserie_proissy`.`ftk09_services` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
